import { expect, test, type Page } from '@playwright/test'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

async function configure(page: Page, connect = true, endpoint = MOCK_ENDPOINT) {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '连接你的设备' })
  await dialog.getByLabel('设备名称').fill('测试工作站')
  await dialog.getByLabel('App Server 地址').fill(endpoint)
  await dialog.getByPlaceholder('App Server 的 Bearer token').fill('memory-only-secret')
  await dialog.getByPlaceholder('例如：/home/me/projects/my-app').fill('/test/project')
  await dialog.getByRole('button', { name: connect ? '保存并连接' : '仅保存', exact: true }).click()
  if (connect) await expect(page.getByTestId('selected-device')).toContainText('测试工作站')
}
async function send(page: Page, text: string) { await page.getByRole('textbox', { name: '发送给 Codex 的消息' }).fill(text); await page.getByRole('button', { name: '发送消息', exact: true }).click() }
async function showSidebar(page: Page) { if (await page.getByRole('button', { name: '打开导航', exact: true }).isVisible() && await page.getByRole('button', { name: '打开导航', exact: true }).getAttribute('aria-expanded') !== 'true') await page.getByRole('button', { name: '打开导航', exact: true }).click() }

test.beforeEach(async ({ page, request }) => { await request.get(MOCK_URL + '/test/reset'); await page.goto('/') })

test('saves profiles across reload without persisting transport tokens', async ({ page }) => {
  await expect(page.getByRole('heading', { name: '有什么需要帮忙？' })).toBeVisible()
  await configure(page, false)
  const storage = await page.evaluate(() => localStorage.getItem('codex-remote.connections.v1'))
  expect(storage).toContain('测试工作站'); expect(storage).not.toContain('memory-only-secret')
  await page.reload()
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '编辑设备 测试工作站' }).click()
  await expect(page.getByLabel('设备名称')).toHaveValue('测试工作站')
  await expect(page.getByPlaceholder('App Server 的 Bearer token')).toHaveValue('')
  await page.getByRole('button', { name: '保存并连接' }).click()
  await expect(page.getByTestId('selected-device')).toContainText('测试工作站')
})

test('initializes the protocol, streams a turn, restores history, and reconnects', async ({ page, request }) => {
  await configure(page)
  await expect(page.getByRole('button', { name: '选择模型' })).toBeEnabled()
  await send(page, '你好')
  await expect(page.getByText('你好，这是通过真实 WebSocket 桥接返回的流式回复。', { exact: true })).toBeVisible()
  await expect(page.locator('.message-user')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '停止生成' })).toHaveCount(0)
  await request.get(MOCK_URL + '/test/disconnect')
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).received.filter((m: string) => m === 'thread/resume').length).toBeGreaterThan(0)
  await expect(page.getByText('你好，这是通过真实 WebSocket 桥接返回的流式回复。', { exact: true })).toBeVisible()
  await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
})

test('waits for explicit approval and handles a server question', async ({ page, request }) => {
  await configure(page)
  await send(page, '测试权限')
  await expect(page.getByRole('heading', { name: '确认执行操作' })).toBeVisible()
  expect((await (await request.get(MOCK_URL + '/test/metrics')).json()).approved).toBe(0)
  await page.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(page.getByText('已获批准，操作完成。', { exact: true })).toBeVisible()
  await send(page, '请向我提问')
  await page.getByRole('radio', { name: /方案 A/ }).check()
  await page.getByRole('button', { name: '提交回答' }).click()
  await expect(page.getByText('已收到你的选择：方案 A', { exact: true })).toBeVisible()
})

test('interrupts an in-progress turn', async ({ page }) => {
  await configure(page)
  await send(page, '长任务')
  await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
  await page.getByRole('button', { name: '停止生成' }).click()
  await expect(page.getByRole('button', { name: '停止生成' })).toHaveCount(0)
  await expect(page.getByText('Codex 正在工作', { exact: true })).toHaveCount(0)
})

test('rejects invalid endpoints and shows recoverable connection failures', async ({ page }) => {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称').fill('错误地址')
  await page.getByLabel('App Server 地址').fill('https://example.com')
  await page.getByRole('button', { name: '保存并连接' }).click()
  await expect(page.getByRole('alert')).toContainText('仅支持')
  await page.getByLabel('App Server 地址').fill('ws://127.0.0.1:1')
  await page.getByRole('button', { name: '保存并连接' }).click()
  await expect(page.getByTestId('selected-device')).toContainText('连接失败')
  await expect(page.locator('.error-banner')).toContainText('无法连接 App Server')
})

test('sanitizes assistant Markdown and never loads remote images', async ({ page }) => {
  const remote: string[] = []
  page.on('request', request => { if (request.url().includes('tracker.example')) remote.push(request.url()) })
  await configure(page)
  await send(page, '安全测试')
  await expect(page.locator('.image-label')).toBeVisible()
  expect(await page.evaluate(() => (window as Window & { __xss?: boolean }).__xss)).toBeUndefined()
  await expect(page.locator('.markdown script, .markdown img, .markdown a[href^="javascript:"]')).toHaveCount(0)
  expect(remote).toEqual([])
})

test('ships an installable manifest and opens the cached shell offline', async ({ page, context, request }) => {
  await configure(page, false)
  const manifest = await (await request.get('/manifest.webmanifest')).json()
  expect(manifest.display).toBe('standalone'); expect(manifest.icons.some((i: { purpose: string }) => i.purpose === 'maskable')).toBe(true)
  for (const icon of manifest.icons) expect((await request.get(icon.src)).ok()).toBe(true)
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: '有什么需要帮忙？' })).toBeVisible()
  expect(await page.evaluate(() => fetch('/api/health').then(() => true).catch(() => false))).toBe(false)
  await expect(page.locator('.top-notice.offline')).toContainText('你仍可查看保存的地址')
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '编辑设备 测试工作站' }).click()
  await expect(page.getByLabel('设备名称')).toHaveValue('测试工作站')
  await context.setOffline(false)
})

test('has no horizontal overflow and captures the desktop and mobile layouts', async ({ page }, testInfo) => {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-welcome.png', fullPage: true })
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称').fill('我的工作站')
  await page.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-connection.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('matches the installed app model and permission interactions', async ({ page, request }, testInfo) => {
  await configure(page)
  await expect(page.locator('.sidebar .device-trigger, .sidebar .connection-section')).toHaveCount(0)
  await expect(page.locator('.workspace-header .device-trigger')).toHaveCount(1)
  await expect(page.locator('.workspace-header .model-trigger')).toHaveCount(0)
  const model = page.getByRole('button', { name: '选择模型', exact: true })
  const reasoning = page.getByRole('button', { name: '思考强度', exact: true })
  await reasoning.click()
  const panel = page.getByRole('dialog', { name: '思考强度', exact: true })
  await expect(panel.getByRole('slider', { name: '思考强度' })).toHaveValue('1')
  await panel.getByRole('slider').press('End')
  await expect(reasoning).toContainText('超高')
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-model-power.png', animations: 'disabled' })
  await panel.getByRole('slider').press('Escape')
  await expect(reasoning).toBeFocused()
  await model.click()
  await page.getByRole('menuitemradio', { name: /轻量模型/ }).click()
  await expect(model).toContainText('轻量模型')
  await expect(reasoning).toContainText('轻度')
  await page.getByRole('button', { name: '更改权限' }).click()
  await page.getByRole('menuitemradio', { name: /完全访问权限/ }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('button', { name: '更改权限' })).toContainText('请求批准')
  await page.getByRole('button', { name: '更改权限' }).click()
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-permissions.png' })
  await page.getByRole('menuitemradio', { name: /帮我批准/ }).click()
  await send(page, '使用所选模型和自动审批')
  await expect(page.getByText('你好，这是通过真实 WebSocket 桥接返回的流式回复。', { exact: true })).toBeVisible()
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const turn = metrics.requests.findLast((r: { method: string }) => r.method === 'turn/start').params
  expect(turn.model).toBe('quick-model'); expect(turn.effort).toBe('low'); expect(turn.approvalsReviewer).toBe('auto_review')
  expect(turn.sandboxPolicy.type).toBe('workspaceWrite'); expect(turn.approvalPolicy).toBe('on-request')
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-conversation.png' })
})

test('keeps both popovers within the viewport and opens only one', async ({ page }) => {
  await configure(page)
  await page.getByRole('button', { name: '选择模型' }).click()
  await page.getByRole('button', { name: '更改权限' }).click()
  await expect(page.locator('.composer-popover')).toHaveCount(1)
  const rect = await page.locator('.composer-popover').boundingBox()
  const viewport = page.viewportSize()!
  expect(rect!.x).toBeGreaterThanOrEqual(0); expect(rect!.x + rect!.width).toBeLessThanOrEqual(viewport.width)
  expect(rect!.y).toBeGreaterThanOrEqual(0); expect(rect!.y + rect!.height).toBeLessThanOrEqual(viewport.height)
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+Shift+M')
  await expect(page.getByRole('dialog', { name: '选择模型' })).toBeVisible()
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('loads a bounded recent page and fetches earlier messages without duplicates', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=paged')
  await configure(page); await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.locator('.message-user')).toHaveCount(30)
  await expect(page.getByRole('button', { name: '思考强度', exact: true })).toContainText('深度')
  await page.getByRole('button', { name: '加载更早消息' }).click()
  await expect(page.locator('.message-user')).toHaveCount(45)
  await expect(page.getByRole('button', { name: '加载更早消息' })).toHaveCount(0)
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.find((r: { method: string }) => r.method === 'thread/resume').params.excludeTurns).toBe(true)
  expect(metrics.requests.filter((r: { method: string }) => r.method === 'thread/items/list').every((r: { params: { limit: number } }) => r.params.limit === 60)).toBe(true)
})

test('cancels a stalled resume and ignores its late response after switching threads', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=slow'); await configure(page); await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消加载' })).toBeVisible()
  await showSidebar(page); await page.getByRole('button', { name: '第二个会话', exact: true }).click()
  await expect(page.getByText('第二个会话的消息。', { exact: true })).toBeVisible()
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).resumed).toContain('existing-thread')
  await expect(page.getByText('第二个会话的消息。', { exact: true })).toBeVisible()
  await expect(page.getByText('正在打开对话…', { exact: true })).toHaveCount(0)
})

test('exits a hung resume with retry and successfully reloads', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=never'); await configure(page)
  await page.clock.install(); await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).received).toContain('thread/resume')
  await page.clock.fastForward(15_100)
  await expect(page.getByRole('heading', { name: '会话未能加载' })).toBeVisible()
  await expect(page.getByRole('button', { name: '取消加载' })).toHaveCount(0)
  await request.get(MOCK_URL + '/test/scenario?name=normal')
  await page.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
})

test('keeps legacy servers usable when pagination is not supported', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=legacy'); await configure(page); await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
})

test('respects permission restrictions and sends an image-only message', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=restricted'); await configure(page)
  await page.getByRole('button', { name: '更改权限' }).click()
  await expect(page.getByRole('menuitemradio', { name: /完全访问权限/ })).toBeDisabled()
  await page.keyboard.press('Escape')
  await page.getByLabel('选择图片', { exact: true }).setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6dwAAAABJRU5ErkJggg==', 'base64') })
  await expect(page.locator('.prompt-editor').getByRole('button', { name: '预览图片 pixel.png' })).toBeVisible()
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.prompt-editor .editor-image-chip')).toHaveCount(0)
  await expect(page.locator('.message-user').getByRole('button', { name: '预览图片 pixel.png' })).toBeVisible()
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.findLast((r: { method: string }) => r.method === 'turn/start').params.input.filter((part: { type: string }) => part.type === 'image')).toHaveLength(1)
})

test('keeps devices only in the header with separate edit and add entries', async ({ page }, testInfo) => {
  await configure(page)
  await expect(page.locator('.sidebar .connection-list, .sidebar .device-option')).toHaveCount(0)
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  const menu = page.getByRole('dialog', { name: '选择设备', exact: true })
  await expect(menu.getByRole('menuitemradio', { name: /测试工作站/ })).toHaveAttribute('aria-checked', 'true')
  await expect(menu.getByRole('menuitem', { name: '编辑设备 测试工作站' })).toBeVisible()
  await expect(menu.getByRole('menuitem', { name: '添加设备', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-devices.png' })
  await menu.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await expect(page.getByLabel('设备名称')).toHaveValue('')
  await page.getByLabel('设备名称').fill('第二台设备')
  await page.getByLabel('App Server 地址').fill('ws://127.0.0.1:4509')
  await page.getByRole('button', { name: '仅保存', exact: true }).click()
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await menu.getByRole('menuitem', { name: '编辑设备 第二台设备' }).click()
  await expect(page.getByLabel('设备名称')).toHaveValue('第二台设备')
  await page.getByLabel('设备名称').fill('远程工作站')
  await page.getByRole('button', { name: '仅保存', exact: true }).click()
  await expect(page.getByRole('button', { name: '选择设备', exact: true })).toContainText('测试工作站')
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await expect(menu.getByRole('menuitemradio', { name: /远程工作站/ })).toBeVisible()
  await menu.getByRole('menuitem', { name: '断开连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('未连接')
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await menu.getByRole('menuitemradio', { name: /测试工作站/ }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
})

test('opens history even while the model list request is stuck', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=model-never'); await configure(page); await showSidebar(page)
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '选择模型' })).toBeDisabled()
})

async function enqueue(page: Page, text: string) { await page.getByRole('textbox', { name: '发送给 Codex 的消息', exact: true }).fill(text); await page.getByRole('button', { name: '加入消息队列', exact: true }).click() }

test('edits and removes queued messages and applies settings changed during a turn', async ({ page, request }) => {
  await configure(page); await send(page, '队列任务开始')
  await expect(page.getByRole('button', { name: '停止生成' })).toBeVisible()
  await enqueue(page, '第二条'); await enqueue(page, '需要移除的消息')
  const queue = page.locator('.composer-island').getByRole('region', { name: '消息队列' })
  await expect(queue.locator('.queue-item')).toHaveCount(2)
  await queue.getByRole('button', { name: '编辑排队消息' }).first().click()
  await queue.getByRole('textbox').fill('修改后的消息')
  await queue.getByRole('button', { name: '保存修改' }).click()
  await queue.getByRole('button', { name: '移除排队消息' }).last().click()
  await page.getByRole('button', { name: '选择模型', exact: true }).click()
  await page.getByRole('menuitemradio', { name: /轻量模型/ }).click()
  await page.getByRole('button', { name: '思考强度', exact: true }).click()
  await page.getByRole('slider', { name: '思考强度' }).press('End')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '更改权限' }).click()
  await page.getByRole('menuitemradio', { name: /帮我批准/ }).click()
  await request.get(MOCK_URL + '/test/finish')
  await expect(queue).toHaveCount(0)
  await expect(page.locator('.message-user').getByText('修改后的消息', { exact: true })).toBeVisible()
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const turns = metrics.requests.filter((r: { method: string }) => r.method === 'turn/start')
  expect(turns).toHaveLength(2)
  expect(turns[1].params).toMatchObject({ model: 'quick-model', effort: 'medium', approvalsReviewer: 'auto_review', approvalPolicy: 'on-request' })
  expect(turns[1].params.input[0].text).toBe('修改后的消息')
})

test('pauses the queue when stopped and retains a failed message for manual retry', async ({ page, request }) => {
  await configure(page); await send(page, '队列任务开始'); await enqueue(page, '发送失败')
  await page.getByRole('button', { name: '停止生成' }).click()
  const queue = page.getByRole('region', { name: '消息队列' })
  await expect(queue).toContainText('已暂停')
  await request.get(MOCK_URL + '/test/scenario?name=queue-fail')
  await queue.getByRole('button', { name: '继续队列' }).click()
  await expect(queue.getByRole('alert')).toContainText('测试发送失败')
  await expect(queue.locator('.queue-item')).toHaveCount(1)
  await request.get(MOCK_URL + '/test/scenario?name=normal')
  await queue.getByRole('button', { name: '继续队列' }).click()
  await expect(queue).toHaveCount(0)
  await expect(page.locator('.message-user').getByText('发送失败', { exact: true })).toBeVisible()
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.filter((r: { method: string }) => r.method === 'turn/start')).toHaveLength(3)
})

test('keeps a background queue bound to its original conversation', async ({ page, request }) => {
  await configure(page); await send(page, '队列任务后台'); await enqueue(page, '后台后续消息')
  const before = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const originalId = before.requests.find((r: { method: string }) => r.method === 'turn/start').params.threadId
  await showSidebar(page); await page.getByRole('button', { name: '第二个会话', exact: true }).click()
  await expect(page.getByText('第二个会话的消息。', { exact: true })).toBeVisible()
  await request.get(MOCK_URL + '/test/finish')
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.filter((r: { method: string }) => r.method === 'turn/start').length).toBe(2)
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.findLast((r: { method: string }) => r.method === 'turn/start').params.threadId).toBe(originalId)
  await expect(page.getByText('第二个会话的消息。', { exact: true })).toBeVisible()
  await expect(page.locator('.message-user').getByText('后台后续消息', { exact: true })).toHaveCount(0)
})

test('renders native reasoning content in the live CLI-style preview and saved history', async ({ page, request }) => {
  await configure(page); await send(page, '思考适配')
  await expect(page.locator('.working-preview')).toContainText('先检查事件顺序')
  await expect(page.locator('.reasoning-snippet')).toContainText('保持原始位置')
  await page.locator('.reasoning summary').click()
  await expect(page.locator('.reasoning .markdown')).toContainText('先检查事件顺序')
  await request.get(MOCK_URL + '/test/finish')
  await expect(page.locator('.reasoning summary')).toContainText(/已思考|思考过程/)
  await showSidebar(page); await page.getByRole('button', { name: '第二个会话', exact: true }).click()
  await showSidebar(page); await page.getByRole('button', { name: '思考适配', exact: true }).click()
  await expect(page.locator('.reasoning-snippet')).toContainText('保持原始位置')
})

test('sends text-image-text in order with inline filenames and hover/click previews', async ({ page, request }, testInfo) => {
  await configure(page)
  const editor = page.locator('#message-input')
  await editor.fill('前文 后文')
  await editor.evaluate(el => { const range = document.createRange(); range.setStart(el.firstChild!, 3); range.collapse(true); window.getSelection()?.removeAllRanges(); window.getSelection()?.addRange(range); el.dispatchEvent(new KeyboardEvent('keyup', { bubbles: true })) })
  await page.getByLabel('选择图片', { exact: true }).setInputFiles({ name: '示意图.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6dwAAAABJRU5ErkJggg==', 'base64') })
  await expect(editor.locator('.editor-image-chip')).toHaveCount(1)
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const bubble = page.locator('.message-user .user-bubble')
  await expect(bubble).toContainText('示意图.png')
  const order = await bubble.locator(':scope > *').allTextContents()
  expect(order).toEqual(['前文 ', '示意图.png', '后文'])
  expect((await bubble.boundingBox())!.height).toBeLessThan(130)
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-inline-images.png', animations: 'disabled' })
  await bubble.getByRole('button', { name: '预览图片 示意图.png' }).hover()
  await expect(page.getByRole('tooltip', { name: '示意图.png', exact: true })).toBeVisible()
  await bubble.getByRole('button', { name: '预览图片 示意图.png' }).click()
  await expect(page.getByRole('dialog', { name: '示意图.png', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '示意图.png', exact: true })).toHaveCount(0)
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const input = metrics.requests.findLast((r: { method: string }) => r.method === 'turn/start').params.input
  expect(input.map((p: { type: string }) => p.type)).toEqual(['text', 'text', 'image', 'text'])
  expect(input[0].text).toBe('前文 '); expect(input[3].text).toBe('后文')
})

test('groups conversations by project and remembers a configurable content width', async ({ page }) => {
  await configure(page); await showSidebar(page)
  await expect(page.locator('.project-group')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '按项目筛选' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '第二个会话', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '第二个会话', exact: true }).click()
  await page.getByRole('button', { name: '设置' }).click()
  await page.getByRole('menuitemradio', { name: '宽屏', exact: true }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('codex-remote.ui.v1')!).contentWidth)).toBe(1280)
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.app-shell')).toHaveCSS('--content-width', '1280px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('shows a truthful context meter with live token details', async ({ page }, testInfo) => {
  await configure(page)
  const editor = page.getByRole('textbox', { name: '发送给 Codex 的消息', exact: true })
  await editor.focus(); await page.getByRole('button', { name: '上下文用量' }).hover()
  await expect(page.getByRole('dialog', { name: '上下文用量' })).toContainText('服务端尚未发送用量')
  await expect(editor).toBeFocused()
  await editor.fill('用量测试'); await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByText('你好，这是通过真实 WebSocket 桥接返回的流式回复。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '上下文用量' }).click()
  const panel = page.getByRole('dialog', { name: '上下文用量' })
  await expect(panel).toContainText('19.1K / 1M'); await expect(panel).toContainText('1.9%')
  await expect(panel.getByText('19K', { exact: true })).toBeVisible()
  await expect(panel.getByText('13.3K', { exact: true })).toBeVisible()
  await expect(panel).toContainText('已包含在输入中')
  await expect(panel).toContainText('服务端未提供系统工具、技能等占比')
  await page.screenshot({ path: 'test-results/' + testInfo.project.name + '-context.png', animations: 'disabled' })
})

test('uses a consistent connected-device hover and right-aligned entry', async ({ page }) => {
  await configure(page)
  const button = page.getByRole('button', { name: '选择设备', exact: true })
  const viewport = page.viewportSize()!, bounds = await button.boundingBox()
  expect(bounds!.x + bounds!.width).toBeGreaterThan(viewport.width - 50)
  await button.click()
  const row = page.locator('.device-option').first()
  await expect(row.locator('.device-status.connected')).toHaveCSS('color', 'rgb(31, 143, 95)')
  await row.locator('.device-select').hover()
  await expect(row.locator('.device-select')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  const background = await row.evaluate(el => getComputedStyle(el).backgroundColor)
  await row.locator('.device-edit').hover()
  expect(await row.evaluate(el => getComputedStyle(el).backgroundColor)).toBe(background)
})
