import { expect, test, type Page } from '../fixtures'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

async function connect(page: Page) {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '连接你的设备' })
  await dialog.getByLabel('设备名称').fill('问题测试设备')
  await dialog.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await dialog.getByPlaceholder('留空使用 ~/codex-remote').fill('/test/project')
  await dialog.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
}
async function ask(page: Page) {
  await page.getByRole('textbox', { name: '发送给 Codex 的消息' }).fill('请确认新命令的设置')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByRole('button', { name: /2 个问题待回答/ })).toBeVisible()
}

test.beforeEach(async ({ page, request }) => { await request.get(MOCK_URL + '/test/reset'); await page.goto('/') })

test('opens async questions with Shift+Left, preserves drafts and submits native replies on desktop and mobile', async ({ page, request }, info) => {
  if (info.project.name === 'mobile') { await page.emulateMedia({ colorScheme: 'dark' }); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark') }
  await request.get(MOCK_URL + '/test/scenario?name=async-question')
  await connect(page); await ask(page)
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' })
  if (info.project.name === 'desktop') {
    await composer.fill('/')
    await expect(page.locator('.island-page-header')).toContainText('命令')
    await composer.press('Shift+ArrowLeft')
    await expect(page.getByRole('heading', { name: '回答 Codex 的问题' })).toBeVisible()
    await page.getByRole('region', { name: 'Codex 待回答的问题' }).getByRole('radio').first().press('Shift+ArrowRight')
    await expect(page.locator('.island-page-header')).toContainText('命令')
    await expect(composer).toHaveText('/')
  }
  await composer.fill('保留这份未发送的草稿')
  await page.screenshot({ path: info.outputPath('async-questions-collapsed.png') })
  if (info.project.name === 'desktop') await composer.press('Shift+ArrowLeft')
  else await page.getByRole('button', { name: /2 个问题待回答/ }).click()
  const pane = page.getByRole('region', { name: 'Codex 待回答的问题' })
  await expect(pane.getByRole('heading', { name: '回答 Codex 的问题' })).toBeVisible()
  await expect(pane.getByRole('radio', { name: '修改代号、插队均仅 Bot 管理员（推荐）', exact: true })).toBeChecked()
  await expect(pane.getByRole('button', { name: '提交回答' })).toBeEnabled()
  await expect(pane.getByRole('button', { name: '提交回答' })).toBeInViewport()
  await page.screenshot({ path: info.outputPath('async-questions-expanded.png') })
  await pane.getByRole('radio', { name: '其他回答', exact: true }).check()
  await pane.getByRole('textbox', { name: '回答，其他回答' }).fill('全部仅管理员')
  await pane.getByRole('textbox', { name: '回答，其他回答' }).press('Shift+ArrowRight')
  await expect(composer).toBeFocused()
  await expect(composer).toHaveText('保留这份未发送的草稿')
  await page.getByRole('button', { name: /2 个问题待回答/ }).click()
  await expect(pane.getByRole('textbox', { name: '回答，其他回答' })).toHaveValue('全部仅管理员')
  await pane.getByRole('button', { name: '提交回答' }).click()
  await expect(pane.getByRole('group', { name: '还有哪些需要补充的要求？' })).toBeVisible()
  await expect(pane.getByRole('textbox', { name: '回答', exact: true })).toBeFocused()
  await pane.getByRole('textbox', { name: '回答', exact: true }).fill('插队操作要记录操作者')
  await pane.getByRole('button', { name: '提交回答' }).click()
  await expect(pane).toHaveCount(0)
  await expect(composer).toHaveText('保留这份未发送的草稿')
  await expect(page.locator('.message-user').last()).toContainText('插队操作要记录操作者')
  await expect(page.locator('.message-list')).not.toContainText('send_user_message_question_reply')
  await expect(page.locator('.island-steers')).not.toContainText('send_user_message_question_reply')
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const submissions = metrics.requests.filter((entry: { method: string }) => entry.method === 'turn/steer')
  expect(submissions).toHaveLength(2)
  const replies = submissions.map((entry: { params: { input: { text: string }[] } }) => JSON.parse(entry.params.input[0]!.text.split('\n')[1]!)[0])
  expect(replies.map((reply: { answer: string }) => reply.answer)).toEqual(['全部仅管理员', '插队操作要记录操作者'])
  expect(replies.map((reply: { questionItemId: string }) => JSON.parse(reply.questionItemId)[2])).toEqual([0, 1])
  await page.reload(); await expect(page.getByTestId('selected-device')).toContainText('已连接')
  await expect(page.locator('.message-user').last()).toContainText('插队操作要记录操作者')
  await expect(page.getByRole('region', { name: 'Codex 待回答的问题' })).toHaveCount(0)
})

test('retains the selected answer and question after rejection and allows an explicit retry', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=async-question-rejected')
  await connect(page); await ask(page)
  await page.getByRole('button', { name: /2 个问题待回答/ }).click()
  const pane = page.getByRole('region', { name: 'Codex 待回答的问题' })
  await pane.getByRole('radio', { name: '其他回答', exact: true }).check()
  await pane.getByRole('textbox', { name: '回答，其他回答' }).fill('全部仅管理员')
  await pane.getByRole('button', { name: '提交回答' }).click()
  await expect(pane.getByRole('alert')).toContainText('测试回答发送失败，请重试')
  await expect(pane.getByRole('textbox', { name: '回答，其他回答' })).toHaveValue('全部仅管理员')
  await expect(pane.getByRole('button', { name: '提交回答' })).toBeEnabled()
  const failed = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(failed.requests.filter((entry: { method: string }) => entry.method === 'turn/steer')).toHaveLength(1)
  await pane.getByRole('button', { name: '提交回答' }).click()
  await expect(pane.getByRole('group', { name: '还有哪些需要补充的要求？' })).toBeVisible()
})

test('restores unanswered questions after reload and answers a completed turn with turn/start', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=async-question-idle')
  await connect(page); await ask(page)
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toHaveCount(0)
  await page.reload(); await expect(page.getByTestId('selected-device')).toContainText('已连接')
  await page.getByRole('button', { name: /2 个问题待回答/ }).click()
  await page.getByRole('region', { name: 'Codex 待回答的问题' }).getByRole('button', { name: '提交回答' }).click()
  await expect(page.getByText('回答已收到。', { exact: true })).toBeVisible()
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.filter((entry: { method: string }) => entry.method === 'turn/steer')).toHaveLength(0)
  expect(metrics.requests.filter((entry: { method: string }) => entry.method === 'turn/start')).toHaveLength(2)
})

test('keeps coexisting async questions and native approvals in one viewport above the composer', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=async-question-with-approval')
  await connect(page); await ask(page)
  await expect(page.getByRole('heading', { name: '确认执行操作' })).toBeVisible()
  await page.getByRole('button', { name: /2 个问题待回答/ }).click()
  const viewport = page.locator('.island-request-viewport.shared')
  await expect(viewport).toBeVisible()
  await expect(page.getByRole('textbox', { name: '发送给 Codex 的消息' })).toBeInViewport()
  await expect(viewport.getByRole('button', { name: '提交回答' })).toBeInViewport()
  await viewport.getByRole('button', { name: '稍后回答，返回输入框' }).click()
  await viewport.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(page.getByRole('heading', { name: '确认执行操作' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /2 个问题待回答/ })).toBeVisible()
})
