import { expect, test, type Page } from '@playwright/test'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

async function configure(page: Page) {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称').fill('命令测试设备')
  await page.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await page.getByPlaceholder('例如：/home/me/projects/my-app').fill('/test/project')
  await page.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
}
const editor = (page: Page) => page.getByRole('textbox', { name: '发送给 Codex 的消息', exact: true })
test.beforeEach(async ({ page, request }) => { await request.get(MOCK_URL + '/test/reset'); await page.goto('/'); await configure(page) })

test('opens and filters slash commands, routes Enter locally, and lets Escape keep the draft', async ({ page, request }) => {
  await editor(page).fill('/')
  await expect(page.getByRole('option', { name: /\/goal/ })).toBeVisible()
  await editor(page).fill('/set')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: '设置', exact: true })).toBeVisible()
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
  await page.keyboard.press('Escape')
  await editor(page).fill('/mo')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('option', { name: /\/model/ })).toHaveCount(0)
  await expect(editor(page)).toHaveText('/mo')
  await editor(page).fill('/model')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('menu', { name: '可用模型' })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
})

test('mentions a remote file at the caret without removing the surrounding text', async ({ page, request }) => {
  await editor(page).fill('请检查 @App 然后说明')
  await editor(page).evaluate(element => {
    const node = element.firstChild!, range = document.createRange()
    range.setStart(node, '请检查 @App'.length); range.collapse(true)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    element.dispatchEvent(new KeyboardEvent('keyup', { key: 'ArrowLeft', bubbles: true }))
  })
  await page.getByRole('option', { name: /App.vue/ }).click()
  await expect(editor(page)).toContainText('请检查 src/App.vue')
  await expect(editor(page)).toContainText('然后说明')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  const search = calls.find((call: any) => call.method === 'fuzzyFileSearch')
  expect(search.params.roots).toEqual(['/test/project'])
  expect(search.params.query).toBe('App')
  const sent = calls.find((call: any) => call.method === 'turn/start')
  expect(sent.params.input.map((part: any) => part.text || '').join('')).toContain('src/App.vue')
})

test('quotes a file path with spaces and does not trigger on email or IME composition', async ({ page, request }) => {
  await editor(page).fill('@计划')
  await page.getByRole('option', { name: /项目 计划.md/ }).click()
  await expect(editor(page)).toContainText('"docs/项目 计划.md"')
  await editor(page).fill('person@example.com')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  const mark = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.length
  await editor(page).evaluate(element => {
    element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
    element.textContent = '@测试'
    element.dispatchEvent(new InputEvent('input', { bubbles: true, isComposing: true }))
    element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, isComposing: true }))
  })
  await expect(page.getByRole('listbox')).toHaveCount(0)
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.slice(mark)
  expect(calls.some((call: any) => ['turn/start', 'fuzzyFileSearch'].includes(call.method))).toBe(false)
})

test('ignores stale file results and keeps drafts when search is unavailable', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=file-search-delayed')
  await editor(page).fill('@App')
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.some((call: any) => call.method === 'fuzzyFileSearch' && call.params.query === 'App')).toBe(true)
  await editor(page).fill('@README')
  await expect(page.getByRole('option', { name: /README.md/ })).toBeVisible()
  await page.getByRole('option', { name: /README.md/ }).click()
  await expect(editor(page)).toContainText('README.md')
  await request.get(MOCK_URL + '/test/scenario?name=file-search-unavailable')
  await editor(page).fill('@missing')
  await expect(page.locator('.prompt-suggestion-status.error')).toContainText(/文件|搜索/)
  await expect(editor(page)).toHaveText('@missing')
})

test('manages a server goal from the island and prioritizes pending approvals', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  await editor(page).fill('/goal 完成项目迁移')
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '设置目标', exact: true })
  await expect(dialog.getByLabel('目标', { exact: true })).toHaveValue('完成项目迁移')
  await dialog.getByLabel('Token 预算', { exact: true }).fill('6000')
  await dialog.getByRole('button', { name: '开始目标', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  const goal = island.getByRole('region', { name: '当前目标', exact: true })
  await expect(goal).toContainText('完成项目迁移')
  await expect(goal).toContainText('进行中')
  await expect(goal).toContainText('1,240')
  await expect(goal).toContainText('4,760')
  await expect(goal).toContainText('12 秒')
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
  expect(calls.find((call: any) => call.method === 'thread/start').params.cwd).toBe('/test/project')
  expect(calls.find((call: any) => call.method === 'thread/goal/set').params).toMatchObject({ objective: '完成项目迁移', status: 'active', tokenBudget: 6000 })
  await goal.getByRole('button', { name: '编辑目标', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑目标', exact: true })
  await edit.getByRole('button', { name: '暂停目标', exact: true }).click()
  await expect(edit.locator('.goal-toolbar [role=status]')).toContainText('已暂停')
  await edit.getByRole('button', { name: '继续目标', exact: true }).click()
  await expect(edit.getByRole('button', { name: '暂停目标', exact: true })).toBeEnabled()
  await edit.getByRole('button', { name: '关闭', exact: true }).last().click()

  await editor(page).fill('多个审批')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(island.locator('.island-header')).toContainText('1 / 2')
  await expect(goal).toHaveCount(0)
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(island.locator('.island-header')).toContainText('1 / 1')
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(goal).toContainText('完成项目迁移')

  await goal.getByRole('button', { name: '编辑目标', exact: true }).click()
  await edit.getByRole('button', { name: '移除目标', exact: true }).click()
  await expect(goal).toContainText('完成项目迁移')
  await edit.getByRole('button', { name: '确认移除', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(goal).toHaveCount(0)
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/goal/clear')).toHaveLength(1)
})

test('restores a goal on reload and keeps it separate from other conversations', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  await editor(page).fill('/goal 保留在服务端的目标')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: '开始目标', exact: true }).click()
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toContainText('保留在服务端的目标')
  await page.reload()
  await expect(page.getByRole('button', { name: '选择模型', exact: true })).toBeEnabled()
  const navigation = page.getByRole('button', { name: '打开导航', exact: true })
  if (await navigation.isVisible()) await navigation.click()
  await page.getByRole('button', { name: '未命名对话', exact: true }).click()
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toContainText('保留在服务端的目标')
  if (await navigation.isVisible()) await navigation.click()
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toHaveCount(0)
})

test('reports disabled goal support while retaining the entered objective', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal-disabled')
  await editor(page).fill('/goal 需要保留的目标')
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '设置目标', exact: true })
  await dialog.getByRole('button', { name: '开始目标', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText(/未启用|不支持/)
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('目标', { exact: true })).toHaveValue('需要保留的目标')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
})

test('groups only neighboring tool kinds and opens real file changes and agents', async ({ page, request, isMobile }) => {
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('查看工具分组')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByText('界面检查完成。', { exact: true })).toBeVisible()
  const activities = page.locator('.message-list > details.activity')
  await expect(activities.filter({ has: page.locator('summary', { hasText: '已读取 2 个文件' }) })).toHaveCount(1)
  const reads = activities.filter({ has: page.locator('summary', { hasText: '已读取 2 个文件' }) })
  await expect(reads).not.toHaveAttribute('open')
  await expect(activities.filter({ has: page.locator('summary', { hasText: '已读取 1 个文件' }) })).toHaveCount(1)
  await reads.locator(':scope > summary').click()
  await expect(reads).toContainText('src/App.vue')
  await expect(reads).toContainText('src/components/PromptEditor.vue')
  expect(await reads.locator(':scope > summary').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgba(0, 0, 0, 0)')

  const changes = page.getByRole('region', { name: '已编辑 4 个文件', exact: true })
  await expect(changes.locator('.changes-file')).toHaveCount(3)
  await changes.getByRole('button', { name: '查看更多（1）', exact: true }).click()
  await expect(changes.locator('.changes-file')).toHaveCount(4)
  await changes.getByRole('button', { name: '查看变更', exact: true }).click()
  await expect(page.locator('.changes-panel').getByLabel('src/App.vue 差异内容', { exact: true })).toContainText('+new line')
  await page.getByRole('button', { name: '关闭变更', exact: true }).click()

  if (isMobile) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  const inspector = page.locator('.thread-inspector')
  await expect(inspector.locator('.inspector-agent')).toHaveCount(6)
  await expect(inspector).toContainText('Zeno')
  await inspector.getByRole('button', { name: '查看更多（3）', exact: true }).click()
  await expect(inspector.locator('.inspector-agent')).toHaveCount(9)
  await expect(inspector).toContainText('Noether')
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'thread/resume' && String(call.params.threadId).startsWith('child-'))).toBe(false)
  await inspector.getByText('创建文件或站点', { exact: true }).click()
  await inspector.getByRole('menuitem', { name: '文档', exact: true }).click()
  await expect(editor(page)).toContainText('请帮我创建一份文档，先向我确认主题和具体要求。')
  await expect(editor(page)).toBeFocused()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  if (isMobile) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  await inspector.locator('.inspector-agent').filter({ hasText: 'Zeno' }).click()
  await expect(inspector.getByRole('region', { name: 'Zeno 详情', exact: true })).toContainText('Zeno 已完成检查。')
  await inspector.getByRole('button', { name: '打开对话', exact: true }).click()
  await expect(page.getByText('Zeno 已完成检查。', { exact: true })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/resume' && call.params.threadId === 'child-0')).toHaveLength(1)
})

test('opens the changes workspace, jumps to files, uses real scopes, and reverses only after confirmation', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('查看变更面板')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const card = page.getByRole('region', { name: '已编辑 4 个文件', exact: true })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '查看变更', exact: true }).click()
  const panel = page.locator('.changes-panel')
  await expect(panel).toBeVisible()
  await expect(panel.locator('.diff-file')).toHaveCount(4)
  await panel.getByRole('button', { name: '跳转到文件', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜索变更文件', exact: true }).fill('README')
  await page.getByRole('menuitem', { name: 'README.md', exact: true }).click()
  await expect(panel.locator('[data-diff-path="README.md"] > button')).toBeFocused()
  const layoutButton = panel.getByRole('button', { name: '差异布局', exact: true })
  if (await layoutButton.isVisible()) { await layoutButton.click(); await page.getByRole('menuitemradio', { name: '并排', exact: true }).click() }
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitemradio', { name: '并排布局', exact: true }).click() }
  await expect(panel.locator('.diff-split')).toHaveCount(4)
  if (await panel.getByRole('button', { name: '折叠全部变更', exact: true }).isVisible()) await panel.getByRole('button', { name: '折叠全部变更', exact: true }).click()
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitem', { name: '折叠全部变更', exact: true }).click() }
  await expect(panel.locator('.diff-code')).toHaveCount(0)
  if (await panel.getByRole('button', { name: '展开全部变更', exact: true }).isVisible()) await panel.getByRole('button', { name: '展开全部变更', exact: true }).click()
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitem', { name: '展开全部变更', exact: true }).click() }
  await expect(panel.locator('.diff-code')).toHaveCount(4)
  await panel.getByRole('button', { name: '变更范围', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '未暂存', exact: true }).click()
  await expect(panel.locator('.diff-file')).toHaveCount(1)
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'command/exec' && call.params.cwd === '/test/project' && call.params.command.includes('diff'))).toBe(true)
  await panel.getByRole('button', { name: '关闭变更', exact: true }).click()
  await card.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(panel.getByText('撤销本轮文件修改？', { exact: true })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'command/exec' && call.params.command[0] === 'python3')).toBe(false)
  await panel.getByRole('button', { name: '确认撤销', exact: true }).click()
  await expect(page.getByRole('region', { name: '已撤销 4 个文件', exact: true })).toHaveCount(1)
  await panel.getByRole('button', { name: '关闭变更', exact: true }).click()
  await page.getByRole('button', { name: '重新应用', exact: true }).click()
  await panel.getByRole('button', { name: '确认重新应用', exact: true }).click()
  await expect(card).toHaveCount(1)
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'command/exec' && call.params.command[0] === 'python3')).toHaveLength(2)
  expect(calls.some((call: any) => call.method === 'thread/revert')).toBe(false)
})

test('hides the preceding file summary when a new turn starts and keeps the history accessible', async ({ page, request }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('创建文件变更')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.file-change-summary')).toBeVisible()
  await request.get(MOCK_URL + '/test/scenario?name=')
  await editor(page).fill('队列任务下一轮')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.file-change-summary')).toHaveCount(0)
  const inspector = page.locator('.thread-inspector')
  if (!await inspector.isVisible()) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  await inspector.getByRole('button', { name: '查看 src/App.vue 的变更', exact: true }).click()
  await expect(page.locator('.changes-panel').getByLabel('src/App.vue 差异内容', { exact: true })).toContainText('+new line')
})

test('Enter steers the active turn while Tab keeps a separate queued message', async ({ page, request }) => {
  await editor(page).fill('队列任务运行中')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  await editor(page).fill('请先处理入口逻辑')
  await page.keyboard.press('Enter')
  await expect(editor(page)).toBeEmpty()
  await editor(page).fill('完成后再检查样式')
  await page.keyboard.press('Tab')
  await expect(editor(page)).toBeEmpty()
  await expect(page.locator('.queue-list')).toContainText('完成后再检查样式')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  const steers = calls.filter((call: any) => call.method === 'turn/steer')
  expect(steers).toHaveLength(1)
  expect(steers[0].params.input[0].text).toBe('请先处理入口逻辑')
})


test('keeps home width fixed, then moves the same editor to the configured conversation width', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '宽屏', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: '关闭窗口', exact: true }).click()
  const area = page.locator('.composer-area')
  await expect(area).toHaveCSS('max-width', '760px')
  await expect(page.locator('.welcome')).toBeVisible()
  const before = (await area.boundingBox())!
  if (page.viewportSize()!.width > 1000) expect(before.width).toBe(760)
  const animation = await editor(page).evaluate(async element => {
    element.dataset.editorIdentity = 'retained'
    element.focus()
    await new Promise(requestAnimationFrame)
    return document.querySelector('.composer-area')!.getAnimations().map(animation => ({
      duration: animation.effect!.getTiming().duration,
      frames: (animation.effect as KeyframeEffect).getKeyframes(),
    }))
  })
  expect(animation.some(item => item.duration === 420 && item.frames.some(frame => String(frame.transform).includes('translate3d')))).toBe(true)
  await editor(page).fill('展开过程中保留的草稿')
  await expect(area).not.toHaveClass(/is-moving/)
  await expect(area).toHaveCSS('max-width', '1280px')
  await expect(editor(page)).toBeFocused()
  await expect(editor(page)).toHaveAttribute('data-editor-identity', 'retained')
  await expect(editor(page)).toHaveText('展开过程中保留的草稿')
  expect((await area.boundingBox())!.y).toBeGreaterThan(before.y)
  await page.getByRole('button', { name: '开启新对话', exact: true }).click()
  await expect(page.locator('.welcome')).toBeVisible()
  await expect(area).not.toHaveClass(/is-moving/)
  await expect(area).toHaveCSS('max-width', '760px')
})

test('opens the conversation layout when a project is selected and respects reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.welcome')).toBeVisible()
  await page.getByRole('button', { name: '工作目录', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'project', exact: true }).click()
  await expect(page.locator('.welcome')).toHaveCount(0)
  await expect(page.locator('.composer-area')).toHaveCSS('max-width', '1080px')
  await expect(page.locator('.composer-area')).not.toHaveClass(/is-moving/)
  expect(await page.locator('.composer-area').evaluate(element => element.getAnimations().length)).toBe(0)
  await expect(editor(page)).toBeFocused()
})

test('renders terminal model errors beside the conversation and retries without losing the draft', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=terminal-error')
  await editor(page).fill('触发一次限流错误')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const failure = page.locator('.message-list .turn-failure')
  await expect(failure).toContainText('429 Too Many Requests')
  await expect(page.locator('.error-banner')).toHaveCount(0)
  await expect(page.locator('.working-status')).toHaveCount(0)
  await editor(page).fill('留在输入框的草稿')
  await request.get(MOCK_URL + '/test/scenario?name=normal')
  await failure.getByRole('button', { name: '重试', exact: true }).click()
  await expect(failure).toHaveCount(0)
  await expect(editor(page)).toHaveText('留在输入框的草稿')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  const starts = calls.filter((call: any) => call.method === 'turn/start')
  expect(starts).toHaveLength(2)
  expect(starts[1].params.input).toEqual([{ type: 'text', text: '继续' }])
})
