import { expect, test, type Page } from '../fixtures'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

async function configure(page: Page) {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称').fill('命令测试设备')
  await page.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await page.getByPlaceholder('留空使用 ~/codex-remote').fill('/test/project')
  await page.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
}
const editor = (page: Page) => page.getByRole('textbox', { name: '发送给 Codex 的消息', exact: true })
test.beforeEach(async ({ page, request }) => { await request.get(MOCK_URL + '/test/reset'); await page.goto('/'); await configure(page) })

test('opens and filters slash commands, routes Enter locally, and lets Escape keep the draft', async ({ page, request }) => {
  await editor(page).fill('/')
  await expect(page.getByRole('option', { name: /\/goal/ })).toBeVisible()
  await editor(page).fill('/set')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: '设置', exact: true })).toBeVisible()
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
  await page.keyboard.press('Escape')
  await editor(page).fill('/mo')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('option', { name: /\/model/ })).toHaveCount(0)
  await expect(editor(page)).toHaveText('/mo')
  await editor(page).fill('/model')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('menu', { name: '可用模型' })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
})

test('mentions a remote file at the caret without removing the surrounding text', async ({ page, request }) => {
  await editor(page).fill('请检查 @App 然后说明')
  await editor(page).evaluate(element => {
    const node = element.firstChild!, range = document.createRange()
    range.setStart(node, '请检查 @App'.length); range.collapse(true)
    const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range)
    element.dispatchEvent(new KeyboardEvent('keyup', { key: 'ArrowLeft', bubbles: true }))
  })
  await page.getByRole('option', { name: /App.vue/ }).click()
  await expect(editor(page)).toContainText('请检查 src/App.vue')
  await expect(editor(page)).toContainText('然后说明')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  const search = calls.find((call: any) => call.method === 'fuzzyFileSearch')
  expect(search.params.roots).toEqual(['/test/project'])
  expect(search.params.query).toBe('App')
  const sent = calls.find((call: any) => call.method === 'turn/start')
  expect(sent.params.input.map((part: any) => part.text || '').join('')).toContain('src/App.vue')
})

test('quotes a file path with spaces and does not trigger on email or IME composition', async ({ page, request }) => {
  await editor(page).fill('@计划')
  await page.getByRole('option', { name: /项目 计划.md/ }).click()
  await expect(editor(page)).toContainText('"docs/项目 计划.md"')
  await editor(page).fill('person@example.com')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  const mark = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.length
  await editor(page).evaluate(element => {
    element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
    element.textContent = '@测试'
    element.dispatchEvent(new InputEvent('input', { bubbles: true, isComposing: true }))
    element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, isComposing: true }))
  })
  await expect(page.getByRole('listbox')).toHaveCount(0)
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.slice(mark)
  expect(calls.some((call: any) => ['turn/start', 'fuzzyFileSearch'].includes(call.method))).toBe(false)
})

test('ignores stale file results and keeps drafts when search is unavailable', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=file-search-delayed')
  await editor(page).fill('@App')
  await expect.poll(async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.some((call: any) => call.method === 'fuzzyFileSearch' && call.params.query === 'App')).toBe(true)
  await editor(page).fill('@README')
  await expect(page.getByRole('option', { name: /README.md/ })).toBeVisible()
  await page.getByRole('option', { name: /README.md/ }).click()
  await expect(editor(page)).toContainText('README.md')
  await request.get(MOCK_URL + '/test/scenario?name=file-search-unavailable')
  await editor(page).fill('@missing')
  await expect(page.locator('.prompt-suggestion-status.error')).toContainText(/文件|搜索/)
  await expect(editor(page)).toHaveText('@missing')
})

test('manages a server goal from the island and prioritizes pending approvals', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  await editor(page).fill('/goal')
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '设置目标', exact: true })
  await dialog.getByLabel('目标', { exact: true }).fill('完成项目迁移')
  await dialog.getByLabel('Token 预算', { exact: true }).fill('6000')
  await dialog.getByRole('button', { name: '开始目标', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  const goal = island.getByRole('region', { name: '当前目标', exact: true })
  await expect(goal).toContainText('完成项目迁移')
  await expect(goal).toContainText('进行中')
  await editor(page).fill('/goal status')
  await page.keyboard.press('Enter')
  await expect(goal).toContainText('1,240')
  await expect(goal).toContainText('4,760')
  await expect(goal).toContainText('12 秒')
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
  expect(calls.find((call: any) => call.method === 'thread/start').params.cwd).toBe('/test/project')
  expect(calls.find((call: any) => call.method === 'thread/goal/set').params).toMatchObject({ objective: '完成项目迁移', status: 'active', tokenBudget: 6000 })
  await goal.getByRole('button', { name: '编辑目标', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑目标', exact: true })
  await edit.getByRole('button', { name: '暂停目标', exact: true }).click()
  await expect(edit.locator('.goal-toolbar [role=status]')).toContainText('已暂停')
  await edit.getByRole('button', { name: '继续目标', exact: true }).click()
  await expect(edit.getByRole('button', { name: '暂停目标', exact: true })).toBeEnabled()
  await edit.getByRole('button', { name: '关闭', exact: true }).last().click()

  await editor(page).fill('多个审批')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(island.locator('.island-header')).toContainText('1 / 2')
  await expect(goal).toHaveCount(0)
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(island.locator('.island-header')).toContainText('1 / 1')
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(goal).toContainText('完成项目迁移')

  await goal.getByRole('button', { name: '编辑目标', exact: true }).click()
  await edit.getByRole('button', { name: '移除目标', exact: true }).click()
  await expect(goal).toContainText('完成项目迁移')
  await edit.getByRole('button', { name: '确认移除', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(goal).toHaveCount(0)
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/goal/clear')).toHaveLength(1)
})

test('starts a goal directly, refills it for editing, and previews status temporarily in the island', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  const objective = '完成迁移，保留  两个空格'
  await editor(page).fill('/goal ' + objective)
  await page.keyboard.press('Enter')
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  const goal = island.getByRole('region', { name: '当前目标', exact: true })
  await expect(goal).toContainText(objective)
  await expect(page.getByRole('dialog', { name: '设置目标', exact: true })).toHaveCount(0)
  await expect(goal.locator('.goal-status-details')).toHaveCount(0)
  const project = island.locator('.composer-directory')
  const [projectBox, goalBox] = await Promise.all([project.boundingBox(), goal.locator('.goal-row').boundingBox()])
  expect(projectBox && goalBox).toBeTruthy()
  expect(Math.abs(projectBox!.y + projectBox!.height / 2 - goalBox!.y - goalBox!.height / 2)).toBeLessThan(12)
  await editor(page).fill('/goal edit')
  await page.keyboard.press('Enter')
  await expect(editor(page)).toHaveText('/goal ' + objective)
  await expect(page.getByRole('dialog', { name: '编辑目标', exact: true })).toHaveCount(0)
  await page.clock.install()
  await editor(page).fill('/goal status')
  await page.keyboard.press('Enter')
  await expect(goal.locator('.goal-status-details')).toContainText('1,240')
  await page.clock.fastForward(8_100)
  await expect(goal.locator('.goal-status-details')).toHaveCount(0)
  await expect(goal).toContainText(objective)
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/goal/set')).toHaveLength(1)
  expect(calls.find((call: any) => call.method === 'thread/goal/set').params).toMatchObject({ objective, status: 'active' })
})

test('resumes a paused goal directly from the compact island', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  await editor(page).fill('/goal 继续已有目标')
  await page.keyboard.press('Enter')
  const goal = page.getByRole('region', { name: '当前目标', exact: true })
  await goal.getByRole('button', { name: '编辑目标', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '编辑目标', exact: true })
  await dialog.getByRole('button', { name: '暂停目标', exact: true }).click()
  await expect(goal).toContainText('已暂停')
  await dialog.getByRole('button', { name: '关闭', exact: true }).last().click()
  await goal.getByRole('button', { name: '恢复目标', exact: true }).click()
  await expect(goal).toContainText('进行中')
  await expect(goal.getByRole('button', { name: '恢复目标', exact: true })).toHaveCount(0)
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/goal/set').at(-1).params).toEqual({ threadId: expect.any(String), status: 'active' })
})

test('keeps a directly entered objective after the server rejects goal support', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal-disabled')
  await editor(page).fill('/goal 需要保留的目标')
  await page.keyboard.press('Enter')
  await expect(editor(page)).toHaveText('/goal 需要保留的目标')
  await expect(page.getByRole('dialog', { name: '设置目标', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: '对话浮岛', exact: true })).toContainText('不支持')
})

test('restores a goal on reload and keeps it separate from other conversations', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal')
  await editor(page).fill('/goal 保留在服务端的目标')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: '设置目标', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toContainText('保留在服务端的目标')
  await page.reload()
  await expect(page.getByRole('button', { name: '选择模型', exact: true })).toBeEnabled()
  const navigation = page.getByRole('button', { name: '打开导航', exact: true })
  if (await navigation.isVisible()) await navigation.click()
  await page.getByRole('button', { name: '未命名对话', exact: true }).click()
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toContainText('保留在服务端的目标')
  if (await navigation.isVisible()) await navigation.click()
  await page.getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('这是保存在远端的会话。', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: '当前目标', exact: true })).toHaveCount(0)
})

test('reports disabled goal support while retaining the entered objective', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=goal-disabled')
  await editor(page).fill('/goal')
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '设置目标', exact: true })
  await dialog.getByLabel('目标', { exact: true }).fill('需要保留的目标')
  await dialog.getByRole('button', { name: '开始目标', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText(/未启用|不支持/)
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('目标', { exact: true })).toHaveValue('需要保留的目标')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
})

test('groups only neighboring tool kinds and opens real file changes and agents', async ({ page, request, isMobile }) => {
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('查看工具分组')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByText('界面检查完成。', { exact: true })).toBeVisible()
  const activities = page.locator('.message-list > details.activity')
  await expect(activities.filter({ has: page.locator('summary', { hasText: '已读取 2 个文件' }) })).toHaveCount(1)
  const reads = activities.filter({ has: page.locator('summary', { hasText: '已读取 2 个文件' }) })
  await expect(reads).not.toHaveAttribute('open')
  await expect(activities.filter({ has: page.locator('summary', { hasText: '已读取 1 个文件' }) })).toHaveCount(1)
  await reads.locator(':scope > summary').click()
  await expect(reads).toContainText('src/App.vue')
  await expect(reads).toContainText('src/components/PromptEditor.vue')
  expect(await reads.locator(':scope > summary').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgba(0, 0, 0, 0)')

  const changes = page.getByRole('region', { name: '已编辑 4 个文件', exact: true })
  await expect(changes.locator('.changes-file')).toHaveCount(3)
  await changes.getByRole('button', { name: '查看更多（1）', exact: true }).click()
  await expect(changes.locator('.changes-file')).toHaveCount(4)
  await changes.getByRole('button', { name: '查看变更', exact: true }).click()
  await expect(page.locator('.changes-panel').getByLabel('src/App.vue 差异内容', { exact: true })).toContainText('+new line')
  await page.getByRole('button', { name: '关闭变更', exact: true }).click()

  if (isMobile) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  const inspector = page.locator('.thread-inspector')
  await expect(inspector.locator('.inspector-agent')).toHaveCount(6)
  await expect(inspector).toContainText('Zeno')
  await inspector.getByRole('button', { name: '查看更多（3）', exact: true }).click()
  await expect(inspector.locator('.inspector-agent')).toHaveCount(9)
  await expect(inspector).toContainText('Noether')
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'thread/resume' && String(call.params.threadId).startsWith('child-'))).toBe(false)
  await inspector.getByText('创建文件或站点', { exact: true }).click()
  await inspector.getByRole('menuitem', { name: '文档', exact: true }).click()
  await expect(editor(page)).toContainText('请帮我创建一份文档，先向我确认主题和具体要求。')
  await expect(editor(page)).toBeFocused()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  if (isMobile) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  await inspector.locator('.inspector-agent').filter({ hasText: 'Zeno' }).click()
  await expect(inspector.getByRole('region', { name: 'Zeno 详情', exact: true })).toContainText('Zeno 已完成检查。')
  await inspector.getByRole('button', { name: '打开对话', exact: true }).click()
  await expect(page.getByText('Zeno 已完成检查。', { exact: true })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'thread/resume' && call.params.threadId === 'child-0')).toHaveLength(1)
})

test('opens the changes workspace, jumps to files, uses real scopes, and reverses only after confirmation', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('查看变更面板')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const card = page.getByRole('region', { name: '已编辑 4 个文件', exact: true })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: '查看变更', exact: true }).click()
  const panel = page.locator('.changes-panel')
  await expect(panel).toBeVisible()
  await expect(panel.locator('.diff-file')).toHaveCount(4)
  await panel.getByRole('button', { name: '跳转到文件', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜索变更文件', exact: true }).fill('README')
  await page.getByRole('menuitem', { name: 'README.md', exact: true }).click()
  await expect(panel.locator('[data-diff-path="README.md"] > button')).toBeFocused()
  const layoutButton = panel.getByRole('button', { name: '差异布局', exact: true })
  if (await layoutButton.isVisible()) { await layoutButton.click(); await page.getByRole('menuitemradio', { name: '并排', exact: true }).click() }
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitemradio', { name: '并排布局', exact: true }).click() }
  await expect(panel.locator('.diff-split')).toHaveCount(4)
  if (await panel.getByRole('button', { name: '折叠全部变更', exact: true }).isVisible()) await panel.getByRole('button', { name: '折叠全部变更', exact: true }).click()
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitem', { name: '折叠全部变更', exact: true }).click() }
  await expect(panel.locator('.diff-code')).toHaveCount(0)
  if (await panel.getByRole('button', { name: '展开全部变更', exact: true }).isVisible()) await panel.getByRole('button', { name: '展开全部变更', exact: true }).click()
  else { await panel.getByRole('button', { name: '更多变更操作', exact: true }).click(); await page.getByRole('menuitem', { name: '展开全部变更', exact: true }).click() }
  await expect(panel.locator('.diff-code')).toHaveCount(4)
  await panel.getByRole('button', { name: '变更范围', exact: true }).click()
  await page.getByRole('menuitemradio', { name: '未暂存', exact: true }).click()
  await expect(panel.locator('.diff-file')).toHaveCount(1)
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'command/exec' && call.params.cwd === '/test/project' && call.params.command.includes('diff'))).toBe(true)
  await panel.getByRole('button', { name: '关闭变更', exact: true }).click()
  await card.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(panel.getByText('撤销本轮文件修改？', { exact: true })).toBeVisible()
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'command/exec' && call.params.command[0] === 'python3')).toBe(false)
  await panel.getByRole('button', { name: '确认撤销', exact: true }).click()
  await expect(page.getByRole('region', { name: '已撤销 4 个文件', exact: true })).toHaveCount(1)
  await panel.getByRole('button', { name: '关闭变更', exact: true }).click()
  await page.getByRole('button', { name: '重新应用', exact: true }).click()
  await panel.getByRole('button', { name: '确认重新应用', exact: true }).click()
  await expect(card).toHaveCount(1)
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'command/exec' && call.params.command[0] === 'python3')).toHaveLength(2)
  expect(calls.some((call: any) => call.method === 'thread/revert')).toBe(false)
})

test('hides the preceding file summary when a new turn starts and keeps the history accessible', async ({ page, request }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await request.get(MOCK_URL + '/test/scenario?name=inspector')
  await editor(page).fill('创建文件变更')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.file-change-summary')).toBeVisible()
  await request.get(MOCK_URL + '/test/scenario?name=')
  await editor(page).fill('队列任务下一轮')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.file-change-summary')).toHaveCount(0)
  const inspector = page.locator('.thread-inspector')
  if (!await inspector.isVisible()) await page.getByRole('button', { name: '对话详情', exact: true }).click()
  await inspector.getByRole('button', { name: '查看 src/App.vue 的变更', exact: true }).click()
  await expect(page.locator('.changes-panel').getByLabel('src/App.vue 差异内容', { exact: true })).toContainText('+new line')
})

test('Enter steers the active turn while Tab keeps a separate queued message', async ({ page, request }) => {
  await editor(page).fill('队列任务运行中')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  await editor(page).fill('请先处理入口逻辑')
  await page.keyboard.press('Enter')
  await expect(editor(page)).toBeEmpty()
  await editor(page).fill('完成后再检查样式')
  await page.keyboard.press('Tab')
  await expect(editor(page)).toBeEmpty()
  await expect(page.locator('.queue-list')).toContainText('完成后再检查样式')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  const steers = calls.filter((call: any) => call.method === 'turn/steer')
  expect(steers).toHaveLength(1)
  expect(steers[0].params.input[0].text).toBe('请先处理入口逻辑')
})


test('keeps home width fixed, then moves the same editor to the configured conversation width', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  if (!await page.getByRole('button', { name: '设置', exact: true }).isVisible()) await page.getByRole('button', { name: /打开导航|展开侧栏/ }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('button', { name: '内容宽度', exact: true }).click()
  await page.getByRole('option', { name: '宽屏', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: '关闭窗口', exact: true }).click()
  const area = page.locator('.composer-area')
  await expect(area).toHaveCSS('max-width', '760px')
  await expect(page.locator('.welcome')).toBeVisible()
  const before = (await area.boundingBox())!
  if (page.viewportSize()!.width > 1000) expect(before.width).toBe(760)
  const animation = await editor(page).evaluate(async element => {
    element.dataset.editorIdentity = 'retained'
    element.focus()
    await new Promise(requestAnimationFrame)
    return document.querySelector('.composer-area')!.getAnimations().map(animation => ({
      duration: animation.effect!.getTiming().duration,
      frames: (animation.effect as KeyframeEffect).getKeyframes(),
    }))
  })
  expect(animation.some(item => item.duration === 420 && item.frames.some(frame => String(frame.transform).includes('translate3d')))).toBe(true)
  await editor(page).fill('展开过程中保留的草稿')
  await expect(area).not.toHaveClass(/is-moving/)
  await expect(area).toHaveCSS('max-width', '1280px')
  await expect(editor(page)).toBeFocused()
  await expect(editor(page)).toHaveAttribute('data-editor-identity', 'retained')
  await expect(editor(page)).toHaveText('展开过程中保留的草稿')
  expect((await area.boundingBox())!.y).toBeGreaterThan(before.y)
  const home = page.locator('.sidebar').getByRole('button', { name: 'Codex Remote 首页', exact: true })
  const navigation = page.getByRole('button', { name: /打开导航|展开侧栏/, exact: true })
  if (await navigation.isVisible() && await navigation.getAttribute('aria-expanded') !== 'true') await navigation.click()
  await home.click()
  await expect(page.locator('.welcome')).toBeVisible()
  await expect(area).not.toHaveClass(/is-moving/)
  await expect(area).toHaveCSS('max-width', '760px')
})

test('opens the conversation layout when a project is selected and respects reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.welcome')).toBeVisible()
  await page.getByRole('button', { name: '工作目录', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'project', exact: true }).click()
  await expect(page.locator('.welcome')).toHaveCount(0)
  await expect(page.locator('.composer-area')).toHaveCSS('max-width', '1080px')
  await expect(page.locator('.composer-area')).not.toHaveClass(/is-moving/)
  expect(await page.locator('.composer-area').evaluate(element => element.getAnimations().length)).toBe(0)
  await expect(editor(page)).toBeFocused()
})

test('renders terminal model errors beside the conversation and retries without losing the draft', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=terminal-error')
  await editor(page).fill('触发一次限流错误')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const failure = page.locator('.message-list .turn-failure')
  await expect(failure).toContainText('429 Too Many Requests')
  await expect(page.locator('.error-banner')).toHaveCount(0)
  await expect(page.locator('.working-status')).toHaveCount(0)
  await editor(page).fill('留在输入框的草稿')
  await request.get(MOCK_URL + '/test/scenario?name=normal')
  await failure.getByRole('button', { name: '重试', exact: true }).click()
  await expect(failure).toHaveCount(0)
  await expect(editor(page)).toHaveText('留在输入框的草稿')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  const starts = calls.filter((call: any) => call.method === 'turn/start')
  expect(starts).toHaveLength(2)
  expect(starts[1].params.input).toEqual([{ type: 'text', text: '继续', text_elements: [] }])
})

for (const completion of [
  { draft: '/', label: '命令', option: /\/goal/, tabs: ['全部', '命令', '技能'] },
  { draft: '@App', label: '提及', option: /App.vue/, tabs: ['全部结果', '文件', '智能体', '对话', '插件', '技能'] },
  { draft: '$aud', label: '技能', option: /Audit/, tabs: ['技能'] },
]) {
  test('replaces project and goal content with the island ' + completion.label + ' list and restores both on Escape', async ({ page, request }) => {
    await request.get(MOCK_URL + '/test/scenario?name=goal')
    await editor(page).fill('/goal 浮岛应保留的目标')
    await page.keyboard.press('Enter')
    await expect(page.getByRole('dialog', { name: '设置目标', exact: true })).toHaveCount(0)
    const island = page.getByRole('region', { name: '对话浮岛', exact: true })
    const goal = island.getByRole('region', { name: '当前目标', exact: true })
    const directory = island.getByRole('button', { name: '工作目录', exact: true })
    await expect(goal).toContainText('浮岛应保留的目标')
    await expect(directory).toBeVisible()
    await editor(page).fill(completion.draft)
    const list = island.getByRole('listbox', { name: completion.label, exact: true })
    await expect(list.getByRole('option', { name: completion.option })).toBeVisible()
    await expect(island.locator('.prompt-suggestions.in-island')).toHaveCount(1)
    await expect(page.locator('.composer .prompt-suggestions')).toHaveCount(0)
    await expect(island.getByRole('tablist', { name: '补全分类', exact: true }).getByRole('tab')).toHaveText(completion.tabs)
    await expect(goal).toBeHidden()
    await expect(directory).toBeHidden()
    await expect(island.locator('.island-page-header')).toHaveText(completion.label)
    await expect(island.getByRole('button', { name: '浮岛上一页', exact: true })).toBeDisabled()
    await expect(island.getByRole('button', { name: '浮岛下一页', exact: true })).toBeDisabled()
    await editor(page).press('Escape')
    await expect(list).toHaveCount(0)
    await expect(island.locator('.island-page-header')).toHaveCount(0)
    await expect(goal).toBeVisible()
    await expect(directory).toBeVisible()
    await expect(editor(page)).toHaveText(completion.draft)
    const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
    expect(calls.some((call: any) => ['turn/start', 'turn/steer'].includes(call.method))).toBe(false)
    expect(calls.find((call: any) => call.method === 'skills/list').params.cwds).toEqual(['/test/project'])
  })
}

test('filters command and mention tabs and stays at tab edges when no other island content exists', async ({ page, request }) => {
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  await editor(page).fill('/')
  const commands = island.getByRole('listbox', { name: '命令', exact: true })
  await expect(commands.getByRole('option', { name: /Audit/ })).toBeVisible()
  await editor(page).press('ArrowLeft')
  await expect(island.getByRole('tab', { name: '全部', exact: true })).toHaveAttribute('aria-selected', 'true')
  await editor(page).press('ArrowRight')
  await expect(island.getByRole('tab', { name: '命令', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(commands.getByRole('option', { name: /\/goal/ })).toBeVisible()
  await expect(commands.getByRole('option', { name: /Audit/ })).toHaveCount(0)
  await editor(page).press('ArrowRight')
  await expect(island.getByRole('tab', { name: '技能', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(commands.getByRole('option', { name: /Audit/ })).toBeVisible()
  await expect(commands.getByRole('option', { name: /\/goal/ })).toHaveCount(0)
  await editor(page).press('ArrowRight')
  await expect(island.getByRole('tab', { name: '技能', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(editor(page)).toHaveText('/')

  await editor(page).fill('@')
  const mentions = island.getByRole('listbox', { name: '提及', exact: true })
  await expect(mentions.getByRole('option', { name: /Browser/ })).toBeVisible()
  await island.getByRole('tab', { name: '对话', exact: true }).click()
  await expect(mentions.getByRole('option', { name: /第二个会话/ })).toBeVisible()
  await expect(mentions.getByRole('option', { name: /Browser/ })).toHaveCount(0)
  await island.getByRole('tab', { name: '插件', exact: true }).click()
  await expect(mentions.getByRole('option', { name: /Browser/ })).toBeVisible()
  await expect(mentions.getByRole('option', { name: /第二个会话/ })).toHaveCount(0)
  await editor(page).press('ArrowRight')
  await expect(island.getByRole('tab', { name: '技能', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(mentions.getByRole('option', { name: /Audit/ })).toBeVisible()
  await expect(mentions.getByRole('option', { name: /disabled-skill|Disabled Skill|已关闭的技能/ })).toHaveCount(0)
  await editor(page).press('ArrowRight')
  await expect(island.getByRole('tab', { name: '技能', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(island.getByRole('button', { name: '浮岛下一页', exact: true })).toBeDisabled()
  await expect(editor(page)).toHaveText('@')
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => ['turn/start', 'turn/steer', 'thread/fork'].includes(call.method))).toBe(false)
})

test('selects an enabled island skill with Tab and sends its native skill metadata', async ({ page, request }) => {
  await editor(page).fill('$')
  const list = page.getByRole('region', { name: '对话浮岛', exact: true }).getByRole('listbox', { name: '技能', exact: true })
  await expect(list.getByRole('option', { name: /Audit/ })).toBeVisible()
  await expect(list.getByRole('option')).toHaveCount(1)
  await page.keyboard.press('Tab')
  await expect(editor(page).locator('.editor-skill-chip')).toHaveAttribute('title', '/test/skills/audit/SKILL.md')
  await expect(list).toHaveCount(0)
  await expect(editor(page)).toBeFocused()
  let calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.some((call: any) => call.method === 'turn/start')).toBe(false)
  await page.keyboard.press('Enter')
  await expect(page.locator('.message-user')).toContainText('audit')
  calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  const starts = calls.filter((call: any) => call.method === 'turn/start')
  expect(starts).toHaveLength(1)
  expect(starts[0].params.input).toEqual(expect.arrayContaining([{ type: 'skill', name: 'audit', path: '/test/skills/audit/SKILL.md' }]))
  expect(starts[0].params.input).toEqual(expect.arrayContaining([{ type: 'text', text: '$audit', text_elements: [{ byteRange: { start: 0, end: 6 }, placeholder: 'audit' }] }]))
})

test('crosses completion tab edges into queue and reasoning pages, then removes pages as content finishes', async ({ page, request }) => {
  await editor(page).fill('思考适配')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  await expect(island.locator('.island-thinking-preview')).toContainText('先检查事件顺序')
  await editor(page).fill('队列任务稍后检查布局')
  await page.keyboard.press('Tab')
  await expect(island.getByRole('region', { name: '消息队列', exact: true })).toContainText('队列任务稍后检查布局')
  await editor(page).fill('@')
  const header = island.locator('.island-page-header')
  const list = island.getByRole('listbox', { name: '提及', exact: true })
  await expect(header).toHaveText('提及 1 / 3')
  await expect(island.getByRole('button', { name: '浮岛上一页', exact: true })).toBeEnabled()
  await island.getByRole('tab', { name: '技能', exact: true }).click()
  await editor(page).press('ArrowRight')
  await expect(header).toHaveText('消息队列 2 / 3')
  await expect(list).toBeHidden()
  await expect(editor(page)).toHaveAttribute('aria-expanded', 'false')
  await expect(editor(page)).not.toHaveAttribute('aria-activedescendant', /.+/)
  await editor(page).press('Enter')
  await editor(page).press('Tab')
  await expect(editor(page)).toHaveText('@')
  await expect(island.locator('.queue-item')).toHaveCount(1)
  await editor(page).press('ArrowRight')
  await expect(header).toHaveText('思考进度 3 / 3')
  await expect(island.locator('.island-thinking-preview')).toBeVisible()
  await editor(page).press('ArrowRight')
  await expect(header).toHaveText('提及 1 / 3')
  await expect(island.getByRole('tab', { name: '全部结果', exact: true })).toHaveAttribute('aria-selected', 'true')
  await editor(page).press('ArrowLeft')
  await expect(header).toHaveText('思考进度 3 / 3')
  await editor(page).press('ArrowLeft')
  await expect(header).toHaveText('消息队列 2 / 3')
  await editor(page).press('ArrowLeft')
  await expect(header).toHaveText('提及 1 / 3')
  await expect(island.getByRole('tab', { name: '技能', exact: true })).toHaveAttribute('aria-selected', 'true')
  const next = island.getByRole('button', { name: '浮岛下一页', exact: true })
  await next.click(); await next.click()
  await expect(header).toHaveText('思考进度 3 / 3')
  const before = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(before.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  expect(before.filter((call: any) => call.method === 'turn/steer')).toHaveLength(0)
  await request.get(MOCK_URL + '/test/finish')
  await expect(page.locator('.message-list .message-user').last()).toContainText('队列任务稍后检查布局')
  await expect(island.getByRole('region', { name: '消息队列', exact: true })).toHaveCount(0)
  await expect(island.locator('.island-thinking-preview')).toHaveCount(0)
  await expect(header).toHaveText('提及')
  await expect(list).toBeVisible()
  await expect(next).toBeDisabled()
  await expect(island.getByRole('button', { name: '浮岛上一页', exact: true })).toBeDisabled()
  await expect(editor(page)).toHaveText('@')
})

test('pages through only pending approvals and returns to completion after the last resolution', async ({ page, request }) => {
  await editor(page).fill('多个审批')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const island = page.getByRole('region', { name: '对话浮岛', exact: true })
  await expect(island.locator('.island-header')).toContainText('1 / 2')
  await editor(page).fill('/')
  const header = island.locator('.island-page-header')
  await expect(header).toHaveText('命令 1 / 3')
  await expect(island.locator('.island-content')).toBeHidden()
  await island.getByRole('button', { name: '浮岛下一页', exact: true }).click()
  await expect(header).toContainText('2 / 3')
  await expect(island.locator('pre').first()).toContainText('printf first')
  await island.getByRole('button', { name: '浮岛下一页', exact: true }).click()
  await expect(header).toContainText('3 / 3')
  await expect(island.locator('pre').first()).toContainText('printf second')
  await island.getByRole('button', { name: '浮岛上一页', exact: true }).click()
  await expect(island.locator('pre').first()).toContainText('printf first')
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(header).toContainText('2 / 2')
  await expect(island.locator('pre').first()).toContainText('printf second')
  await island.getByRole('button', { name: '允许这一次', exact: true }).click()
  await expect(header).toHaveText('命令')
  await expect(island.getByRole('listbox', { name: '命令', exact: true })).toBeVisible()
  await expect(island.getByRole('button', { name: '浮岛上一页', exact: true })).toBeDisabled()
  await expect(island.getByRole('button', { name: '浮岛下一页', exact: true })).toBeDisabled()
  await expect(editor(page)).toHaveText('/')
  const result = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(result.approved).toBe(2)
  expect(result.requests.filter((call: any) => call.method === 'turn/start')).toHaveLength(1)
  expect(result.requests.filter((call: any) => call.method === 'turn/steer')).toHaveLength(0)
})

test('hides Stop for a busy draft and restores it when the draft is cleared', async ({ page, request }) => {
  const stop = page.getByRole('button', { name: '停止生成', exact: true })
  await expect(stop).toHaveCount(0)
  await editor(page).fill('队列任务保持忙碌')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(stop).toBeVisible()
  await editor(page).fill('   ')
  await expect(stop).toBeVisible()
  await editor(page).fill('尚未发送的插话')
  await expect(stop).toHaveCount(0)
  await expect(page.getByRole('button', { name: '发送到当前任务', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: '加入消息队列', exact: true })).toBeEnabled()
  await editor(page).fill('')
  await expect(stop).toBeVisible()
  await expect(page.getByRole('button', { name: '发送到当前任务', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '加入消息队列', exact: true })).toHaveCount(0)
  await stop.click()
  await expect(stop).toHaveCount(0)
  await expect(page.getByRole('button', { name: '发送消息', exact: true })).toBeDisabled()
  const calls = (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests
  expect(calls.filter((call: any) => /^turn\/(start|steer|interrupt)$/.test(call.method)).map((call: any) => call.method)).toEqual(['turn/start', 'turn/interrupt'])
})


test('recalls prior inputs with Up and restores the draft with Down', async ({ page }) => {
  for (const input of ['历史输入一', '历史输入二']) {
    await editor(page).fill(input)
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await expect(page.locator('.message-user').last()).toContainText(input)
    await expect(page.locator('.working-status')).toHaveCount(0)
  }
  await editor(page).focus()
  await page.keyboard.press('ArrowUp'); await expect(editor(page)).toHaveText('历史输入二')
  await page.keyboard.press('ArrowUp'); await expect(editor(page)).toHaveText('历史输入一')
  await page.keyboard.press('ArrowDown'); await expect(editor(page)).toHaveText('历史输入二')
  await page.keyboard.press('ArrowDown'); await expect(editor(page)).toBeEmpty()
  await editor(page).fill('尚未发送的草稿')
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('ArrowUp'); await expect(editor(page)).toHaveText('历史输入二')
  await page.keyboard.press('ArrowDown'); await expect(editor(page)).toHaveText('尚未发送的草稿')
})

test('retains normal caret movement, selection and completion-menu arrow handling', async ({ page }) => {
  await editor(page).fill('已发送的输入')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.message-user').last()).toContainText('已发送的输入')
  await expect(page.locator('.working-status')).toHaveCount(0)
  await editor(page).fill('第一行\n第二行')
  await page.keyboard.press('ArrowUp'); await expect(editor(page)).toHaveText('第一行\n第二行')
  await page.keyboard.press('Control+A'); await page.keyboard.press('ArrowUp')
  await expect(editor(page)).toHaveText('第一行\n第二行')
  await editor(page).fill('/')
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.keyboard.press('ArrowUp'); await expect(editor(page)).toHaveText('/')
  await page.keyboard.press('Escape')
  await editor(page).fill(''); await page.keyboard.press('ArrowUp')
  await editor(page).press('End'); await page.keyboard.type(' 修改')
  await page.keyboard.press('ArrowDown'); await expect(editor(page)).toHaveText('已发送的输入 修改')
})

test('shows frozen completed work time next to the summary copy button', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/scenario?name=work-duration')
  await editor(page).fill('查看工作用时')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  const summary = page.locator('.message-agent').last()
  await expect(summary.locator('.work-duration')).toHaveText('工作了 2 分 18 秒')
  const footer = summary.locator('.agent-message-actions')
  const [copy, duration] = await Promise.all([footer.getByRole('button', { name: '复制回复' }).boundingBox(), footer.locator('.work-duration').boundingBox()])
  expect(copy && duration).toBeTruthy()
  expect(duration!.x).toBeGreaterThanOrEqual(copy!.x + copy!.width)
  expect(Math.abs(duration!.y + duration!.height / 2 - copy!.y - copy!.height / 2)).toBeLessThan(3)
  await editor(page).fill('下一轮')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.work-duration').first()).toHaveText('工作了 2 分 18 秒')
})
