import { expect, test, type Page } from '../fixtures'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

async function connect(page: Page) {
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '连接你的设备' })
  await dialog.getByLabel('设备名称').fill('附件测试设备')
  await dialog.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await dialog.getByPlaceholder('留空使用 ~/codex-remote').fill('/test/project')
  await dialog.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
}
test.beforeEach(async ({ page, request }) => { await request.get(MOCK_URL + '/test/reset'); await page.goto('/'); await connect(page) })

test('accepts any file type, preserves bytes and order, and restores file chips from history', async ({ page, request }, info) => {
  if (info.project.name === 'mobile') await page.emulateMedia({ colorScheme: 'dark' })
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' }), input = page.getByLabel('选择附件', { exact: true })
  expect(await input.getAttribute('accept')).toBeNull()
  await composer.fill('先看这些文件：')
  const bytes = Buffer.from(Array.from({ length: 262144 * 2 + 137 }, (_, i) => i % 256))
  await input.setInputFiles([
    { name: '说明.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7\ncontent') },
    { name: '数据.任意扩展名', mimeType: '', buffer: bytes },
    { name: '压缩包.zip', mimeType: 'application/zip', buffer: Buffer.from([80, 75, 0, 255, 1]) },
  ])
  await expect(composer.locator('.editor-file-chip')).toHaveCount(3)
  await expect(page.getByRole('status').filter({ hasText: '正在上传' })).toHaveCount(0)
  await composer.press('End'); await composer.press('ArrowRight'); await page.keyboard.insertText(' 然后总结。')
  await page.screenshot({ path: info.outputPath('file-attachments-draft.png') })
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.message-user').getByRole('button', { name: '查看文件 数据.任意扩展名', exact: true })).toBeVisible()
  await expect(page.locator('.message-user')).toContainText('然后总结。')
  await expect(page.locator('body')).not.toContainText('codex_remote_file')
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  const turn = metrics.requests.find((entry: { method: string }) => entry.method === 'turn/start')
  const refs = turn.params.input.filter((part: { text?: string }) => part.text?.startsWith('<codex_remote_file>')).map((part: { text: string }) => JSON.parse(part.text.split('\n')[1]!))
  expect(refs.map((file: { name: string }) => file.name)).toEqual(['说明.pdf', '数据.任意扩展名', '压缩包.zip'])
  const stored = await (await request.get(MOCK_URL + '/test/uploaded-file?path=' + encodeURIComponent(refs[1].path))).json()
  expect(Buffer.from(stored.dataBase64, 'base64')).toEqual(bytes)
  await page.reload(); await expect(page.getByTestId('selected-device')).toContainText('已连接')
  await expect(page.locator('.message-user').getByRole('button', { name: '查看文件 数据.任意扩展名', exact: true })).toBeVisible()
  await expect(page.locator('body')).not.toContainText('codex_remote_file')
  await page.getByRole('textbox', { name: '发送给 Codex 的消息' }).press('ArrowUp')
  await expect(page.getByRole('textbox', { name: '发送给 Codex 的消息' }).locator('.editor-file-chip')).toHaveCount(3)
})

test('pastes and drops non-image files and removes them without losing the draft', async ({ page }) => {
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' })
  await composer.fill('保留原来的文字')
  await composer.evaluate(element => {
    const data = new DataTransfer(); data.items.add(new File(['a,b\n1,2'], '数据.csv', { type: 'text/csv' }))
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
  })
  await expect(composer.locator('.editor-file-chip')).toHaveCount(1)
  await composer.evaluate(element => {
    const data = new DataTransfer(); data.items.add(new File(['\x00binary'], '没有扩展名', { type: 'application/octet-stream' }))
    element.dispatchEvent(new DragEvent('drop', { dataTransfer: data, bubbles: true, cancelable: true }))
  })
  await expect(composer.locator('.editor-file-chip')).toHaveCount(2)
  await composer.getByRole('button', { name: '移除文件 数据.csv', exact: true }).press('Enter')
  await expect(composer.locator('.editor-file-chip')).toHaveCount(1)
  await expect(composer).toContainText('保留原来的文字')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.message-user').getByRole('button', { name: '查看文件 没有扩展名', exact: true })).toBeVisible()
})

test('keeps file identity when queuing and editing a pending message', async ({ page }, info) => {
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' })
  await composer.fill('队列任务开始'); await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  await composer.fill('稍后处理这个文件')
  await page.getByLabel('选择附件', { exact: true }).setInputFiles({ name: '队列.docx', mimeType: 'application/octet-stream', buffer: Buffer.from('doc content') })
  await expect(composer.locator('.editor-file-chip')).toHaveCount(1)
  await composer.press('Tab')
  const queue = page.getByRole('region', { name: '消息队列', exact: true })
  await expect(queue.getByRole('button', { name: '查看文件 队列.docx', exact: true })).toBeVisible()
  await expect(queue.locator('.inline-file')).toContainText('11 B')
  await queue.getByRole('button', { name: '编辑排队消息', exact: true }).click()
  const editor = queue.getByRole('textbox')
  await editor.evaluate(element => {
    const data = new DataTransfer(); data.items.add(new File(['csv'], '追加.csv', { type: 'text/csv' }))
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
  })
  await expect(editor.locator('.editor-file-chip')).toHaveCount(2)
  await queue.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(queue.getByRole('button', { name: '查看文件 追加.csv', exact: true })).toBeVisible()
  await expect(queue.getByRole('button', { name: '查看文件 队列.docx', exact: true })).toBeInViewport()
  await expect(queue.getByRole('button', { name: '查看文件 追加.csv', exact: true })).toBeInViewport()
  await page.screenshot({ path: info.outputPath('file-attachments-queue.png') })
})

test('retains uploaded files when revising a submitted message', async ({ page }) => {
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' })
  await composer.fill('请检查附件')
  await page.getByLabel('选择附件', { exact: true }).setInputFiles({ name: '原文件.txt', mimeType: 'text/plain', buffer: Buffer.from('original file') })
  await expect(composer.locator('.editor-file-chip')).toHaveCount(1)
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toHaveCount(0)
  await page.locator('.message-user').first().hover()
  await page.getByRole('button', { name: '编辑消息', exact: true }).click()
  const editor = page.getByRole('textbox', { name: '编辑消息内容', exact: true })
  await expect(editor.locator('.editor-file-chip')).toHaveCount(1)
  await editor.evaluate(element => {
    const data = new DataTransfer(); data.items.add(new File(['extra'], '补充.json', { type: 'application/json' }))
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
  })
  await expect(editor.locator('.editor-file-chip')).toHaveCount(2)
  await page.getByRole('button', { name: '保存并重新发送', exact: true }).click()
  await expect(page.locator('.message-user').getByRole('button', { name: '查看文件 原文件.txt', exact: true })).toBeVisible()
  await expect(page.locator('.message-user').getByRole('button', { name: '查看文件 补充.json', exact: true })).toBeVisible()
})

test('upload rejection and cancellation preserve the message and never submit an incomplete file', async ({ page, request }) => {
  const composer = page.getByRole('textbox', { name: '发送给 Codex 的消息' }), input = page.getByLabel('选择附件', { exact: true })
  await composer.fill('不要丢失这份草稿')
  await request.get(MOCK_URL + '/test/scenario?name=file-upload-error')
  await input.setInputFiles({ name: '上传失败.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: Buffer.from('data') })
  await expect(page.getByRole('alert')).toContainText('测试文件上传失败')
  await expect(composer).toHaveText('不要丢失这份草稿')
  await expect(composer.locator('.editor-file-chip')).toHaveCount(0)
  await request.get(MOCK_URL + '/test/scenario?name=file-upload-slow')
  await input.setInputFiles({ name: '取消上传.bin', mimeType: 'application/octet-stream', buffer: Buffer.alloc(524289, 1) })
  await page.getByRole('button', { name: '取消添加附件', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消添加附件', exact: true })).toHaveCount(0)
  await expect(composer).toHaveText('不要丢失这份草稿')
  await expect(composer.locator('.editor-file-chip')).toHaveCount(0)
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.some((entry: { method: string }) => entry.method === 'turn/start')).toBe(false)
  expect(metrics.requests.some((entry: { method: string; params: { command?: string[] } }) => entry.method === 'command/exec' && entry.params.command?.[5] === 'finish')).toBe(false)
})
