import { expect, test } from '../fixtures'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

test('displays remote-device and HTTP images, supports zoom, retries failures and resolves document-relative images', async ({ page, request }, info) => {
  await request.get(MOCK_URL + '/test/reset')
  await request.get(MOCK_URL + '/test/scenario?name=markdown-images')
  const incorrectRequests: string[] = [], browserErrors: string[] = []
  page.on('pageerror', error => browserErrors.push(error.message))
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/tmp/')) incorrectRequests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称', { exact: true }).fill('图片测试设备')
  await page.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await page.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
  const toggle = page.getByRole('button', { name: /打开导航|展开侧栏/, exact: true })
  if (await toggle.isVisible() && await toggle.getAttribute('aria-expanded') !== 'true') await toggle.click()
  await page.locator('.sidebar').getByRole('button', { name: '已有项目分析', exact: true }).click()
  const image = page.getByRole('img', { name: '单列服务器列表预览', exact: true })
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(640)
  expect(await image.evaluate(img => img.getBoundingClientRect().right <= window.innerWidth)).toBe(true)
  const remote = page.getByRole('img', { name: '远程图片', exact: true })
  await expect(remote).toBeVisible()
  await expect.poll(() => remote.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
  await page.getByRole('button', { name: '放大图片 单列服务器列表预览', exact: true }).click()
  const preview = page.getByRole('dialog', { name: '单列服务器列表预览', exact: true })
  await expect(preview).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(preview).toBeHidden()
  await expect(page.getByRole('button', { name: '放大图片 单列服务器列表预览', exact: true })).toBeFocused()
  await expect(page.locator('.markdown-image-status').filter({ hasText: '缺失图片' })).toContainText('文件不存在')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.locator('.markdown-image-status').filter({ hasText: '缺失图片' })).toContainText('文件不存在')
  await page.screenshot({ path: info.outputPath('markdown-images-chat.png') })
  await page.getByRole('button', { name: '图片说明', exact: true }).click()
  const panel = page.getByRole('complementary', { name: '文件预览', exact: true })
  await expect(panel.getByRole('img', { name: '相对路径图片', exact: true })).toBeVisible()
  expect(incorrectRequests).toEqual([])
  expect(browserErrors).toEqual([])
  await page.screenshot({ path: info.outputPath('markdown-images.png') })
})
