import { expect, test } from '../fixtures'
import { MOCK_ENDPOINT, MOCK_URL } from '../config'

test.beforeEach(async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/reset')
  await request.get(MOCK_URL + '/test/scenario?name=rich-content')
  await page.goto('/')
  await page.getByRole('button', { name: '选择设备', exact: true }).click()
  await page.getByRole('menuitem', { name: '添加设备', exact: true }).click()
  await page.getByLabel('设备名称').fill('内容测试设备')
  await page.getByLabel('App Server 地址').fill(MOCK_ENDPOINT)
  await page.getByRole('button', { name: '保存并连接', exact: true }).click()
  await expect(page.getByTestId('selected-device')).toContainText('已连接')
  const nav = page.getByRole('button', { name: /打开导航|展开侧栏/, exact: true })
  if (await nav.isVisible() && await nav.getAttribute('aria-expanded') !== 'true') await nav.click()
  await page.locator('.sidebar').getByRole('button', { name: '已有项目分析', exact: true }).click()
  await expect(page.getByText('常见内容：', { exact: true })).toBeVisible()
})

test('renders native images/audio, Mermaid, formulas, tasks and tool media', async ({ page }, info) => {
  const image = page.getByRole('button', { name: '预览图片 历史图片', exact: true })
  await expect.poll(() => image.locator('img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1)
  await image.click()
  await expect(page.getByRole('dialog', { name: '历史图片', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭图片预览', exact: true }).click()
  const audio = page.locator('audio[aria-label="历史音频"]')
  await expect.poll(() => audio.evaluate((audio: HTMLAudioElement) => audio.duration)).toBeGreaterThan(0)
  await expect(page.getByRole('img', { name: 'Mermaid 图表', exact: true })).toBeVisible()
  await expect.poll(() => page.getByRole('img', { name: 'Mermaid 图表', exact: true }).evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
  const diagramSource = await page.getByRole('img', { name: 'Mermaid 图表', exact: true }).getAttribute('src')
  const diagram = decodeURIComponent(diagramSource!.slice(diagramSource!.indexOf(',') + 1))
  expect(diagram).toContain('用户输入'); expect(diagram).toContain('显示结果'); expect(diagram).not.toContain('foreignObject')
  expect(await page.getByRole('img', { name: 'Mermaid 图表', exact: true }).evaluate(img => img.getBoundingClientRect().width)).toBeLessThan(300)
  await page.locator('.mermaid-diagram').screenshot({ path: info.outputPath('mermaid.png') })
  await expect(page.locator('.katex')).toHaveCount(2)
  const tasks = page.locator('.task-list-item-checkbox')
  await expect(tasks).toHaveCount(2); await expect(tasks.first()).toBeChecked(); await expect(tasks.first()).toBeDisabled()
  await page.getByText('测试媒体 · 展示结果', { exact: true }).click()
  await expect(page.getByRole('img', { name: '工具图片', exact: true })).toBeVisible()
  await expect(page.getByText('工具返回内容', { exact: true })).toBeVisible()
  await page.getByText('动态媒体', { exact: true }).click()
  await expect(page.getByRole('img', { name: '图片 1', exact: true })).toBeVisible()
  await page.getByText('生成图片', { exact: true }).click()
  await expect(page.getByRole('img', { name: '生成的图片', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('rich-content.png') })
})

test('previews sanitized SVG, PDF pages and audio without executing SVG or loading its resources', async ({ page }, info) => {
  const blocked: string[] = []
  page.on('request', request => { if (request.url().includes('blocked.example')) blocked.push(request.url()) })
  await expect(page.getByRole('img', { name: 'SVG 图片', exact: true })).toBeVisible()
  await expect.poll(() => page.getByRole('img', { name: 'SVG 图片', exact: true }).evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(320)
  const src = await page.getByRole('img', { name: 'SVG 图片', exact: true }).getAttribute('src')
  const svg = decodeURIComponent(src!.slice(src!.indexOf(',') + 1))
  expect(svg).not.toContain('<script'); expect(svg).not.toContain('onload'); expect(svg).not.toContain('blocked.example')
  expect(await page.evaluate(() => (window as any).__svgXss)).toBeUndefined()
  await page.getByRole('button', { name: 'SVG 文件', exact: true }).click()
  const panel = page.getByRole('complementary', { name: '文件预览', exact: true })
  await expect(panel.getByRole('img', { name: 'result.svg', exact: true })).toBeVisible()
  await panel.getByRole('button', { name: '关闭文件预览', exact: true }).click()
  await page.getByRole('button', { name: 'PDF 文件', exact: true }).click()
  const canvas = panel.locator('canvas')
  await expect(canvas).toBeVisible()
  await expect(panel.getByText('1 / 2', { exact: true })).toBeVisible()
  await expect.poll(() => canvas.evaluate((canvas: HTMLCanvasElement) => Array.from(canvas.getContext('2d')!.getImageData(Math.floor(canvas.width * .4), Math.floor(canvas.height * .6), 1, 1).data))).toEqual([255, 0, 0, 255])
  const first = await canvas.evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  await panel.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(panel.getByText('2 / 2', { exact: true })).toBeVisible()
  await expect.poll(() => canvas.evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())).not.toBe(first)
  await expect.poll(() => canvas.evaluate((canvas: HTMLCanvasElement) => Array.from(canvas.getContext('2d')!.getImageData(Math.floor(canvas.width * .4), Math.floor(canvas.height * .6), 1, 1).data))).toEqual([0, 0, 255, 255])
  await panel.screenshot({ path: info.outputPath('pdf-preview.png') })
  await panel.getByRole('button', { name: '关闭文件预览', exact: true }).click()
  await page.getByRole('button', { name: '音频文件', exact: true }).click()
  await expect.poll(() => panel.locator('audio').evaluate((audio: HTMLAudioElement) => audio.duration)).toBeGreaterThan(0)
  expect(blocked).toEqual([])
})

test('renders native audio in the message editor without converting it into an image', async ({ page }) => {
  await page.getByRole('button', { name: '编辑消息', exact: true }).click()
  await expect(page.locator('.message-revision-editor')).toBeVisible()
  await page.locator('.message-revision-editor').getByRole('button', { name: '播放音频 历史音频', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '历史音频', exact: true })
  await expect(dialog).toBeVisible()
  await expect.poll(() => dialog.locator('audio').evaluate((audio: HTMLAudioElement) => audio.duration)).toBeGreaterThan(0)
  await expect(dialog.locator('img')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.locator('.message-revision-editor').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.locator('.message-revision-editor')).toHaveCount(0)
})

test('keeps MCP forms pending until an explicit, validated answer and preserves typed values', async ({ page, request }, info) => {
  await request.get(MOCK_URL + '/test/elicitation')
  const form = page.locator('.elicitation-form')
  await expect(form.getByText('请填写发布信息', { exact: true })).toBeVisible()
  const responses = async () => (await (await request.get(MOCK_URL + '/test/metrics')).json()).requests.filter((entry: any) => entry.method === 'elicitation/response')
  expect(await responses()).toEqual([])
  await form.getByRole('button', { name: '提交', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('标题')
  await form.getByLabel('标题', { exact: false }).fill('发布说明')
  await form.getByLabel('数量', { exact: false }).fill('2')
  await form.getByLabel('公开发布', { exact: false }).selectOption('false')
  await form.getByLabel('标签', { exact: false }).selectOption(['a', 'b'])
  await form.screenshot({ path: info.outputPath('mcp-form.png') })
  await form.getByRole('button', { name: '提交', exact: true }).click()
  await expect(form).toHaveCount(0)
  expect((await responses())[0].params.result).toEqual({ action: 'accept', content: { title: '发布说明', count: 2, confirm: false, labels: ['a', 'b'] }, _meta: null })
})

test('MCP URL requests open only on user action and support explicit cancellation', async ({ page, request }) => {
  await request.get(MOCK_URL + '/test/elicitation?mode=url')
  const form = page.locator('.elicitation-form')
  await expect(form.getByRole('link')).toHaveAttribute('href', 'https://auth.example/authorize')
  expect(page.context().pages()).toHaveLength(1)
  await page.route('https://auth.example/**', route => route.fulfill({ body: '授权完成', contentType: 'text/html' }))
  const opened = page.waitForEvent('popup')
  await form.getByRole('link').click()
  const popup = await opened; await popup.close()
  await form.getByRole('button', { name: '取消', exact: true }).click()
  await expect(form).toHaveCount(0)
  const metrics = await (await request.get(MOCK_URL + '/test/metrics')).json()
  expect(metrics.requests.find((entry: any) => entry.method === 'elicitation/response').params.result).toEqual({ action: 'cancel', content: null, _meta: null })
})
